using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Blocks.Gameplay.Core;
using System.Collections.Generic;

/// <summary>
/// Custom editor for <see cref="StatsConfig"/> that provides code generation functionality.
/// Scans all StatsConfig assets in the project and generates a StatKeys.cs file containing
/// pre-hashed constants for efficient stat lookups.
/// </summary>
[CustomEditor(typeof(StatsConfig))]
public class StatsConfigEditor : Editor
{
    #region Unity Methods

    /// <summary>
    /// Draws the default inspector with an additional button to generate StatKeys.cs.
    /// </summary>
    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();

        EditorGUILayout.Space(20);
        if (GUILayout.Button("Generate/Update StatKeys.cs", GUILayout.Height(40)))
        {
            GenerateStatKeysFromAllConfigs();
        }
    }

    #endregion

    #region Private Methods

    private void GenerateStatKeysFromAllConfigs()
    {
        string folderPath = Application.dataPath + "/Core/Scripts/Runtime/Generated";
        string filePath = folderPath + "/StatKeys.cs";

        if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);

        var guids = AssetDatabase.FindAssets("t:StatsConfig");

        // Track all unique stats across all configs to detect field name collisions
        var allStats = new Dictionary<string, (string statName, string sourcePath)>();
        int duplicateCount = 0;

        foreach (var guid in guids)
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var config = AssetDatabase.LoadAssetAtPath<StatsConfig>(path);

            if (config == null || config.stats == null) continue;

            foreach (var stat in config.stats)
            {
                if (stat == null || string.IsNullOrEmpty(stat.statName)) continue;

                // Sanitize stat name to valid C# identifier by removing invalid characters
                string fieldName = System.Text.RegularExpressions.Regex.Replace(stat.statName, @"[^a-zA-Z0-9_]", "");
                if (char.IsDigit(fieldName[0])) fieldName = "_" + fieldName;

                if (allStats.ContainsKey(fieldName))
                {
                    // Warn about true collisions where different stat names map to the same field name
                    if (allStats[fieldName].statName != stat.statName)
                    {
                        Debug.LogWarning($"[StatKeys] Field name collision: '{stat.statName}' in '{path}' conflicts with '{allStats[fieldName].statName}' from '{allStats[fieldName].sourcePath}'");
                        duplicateCount++;
                    }
                }
                else
                {
                    allStats[fieldName] = (stat.statName, path);
                }
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// ========================================================");
        sb.AppendLine("// AUTO-GENERATED FILE. DO NOT MODIFY MANUALLY.");
        sb.AppendLine("// Generated by StatsConfigEditor from all StatsConfig assets");
        sb.AppendLine("// ========================================================");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace Blocks.Gameplay.Core");
        sb.AppendLine("{");
        sb.AppendLine("    public static class StatKeys");
        sb.AppendLine("    {");

        foreach (var kvp in allStats)
        {
            string fieldName = kvp.Key;
            string statName = kvp.Value.statName;
            string sourcePath = kvp.Value.sourcePath;

            sb.AppendLine($"        /// <summary>Hash for '{statName}' (from {sourcePath})</summary>");
            sb.AppendLine($"        public static readonly int {fieldName} = Animator.StringToHash(\"{statName}\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
        AssetDatabase.Refresh();

        string message = $"StatKeys.cs updated! Generated {allStats.Count} keys from {guids.Length} StatsConfig asset(s).";
        if (duplicateCount > 0)
        {
            Debug.LogWarning($"<color=#FFFF44><b>{message}</b></color> ({duplicateCount} collision(s) detected - check warnings above)");
        }
        else
        {
            Debug.Log($"<color=#44FF44><b>{message}</b></color>");
        }
    }

    #endregion
}
